name: First pipeline

on:
  push:
    branches:
      - main
      - production

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: Terraform plan
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'nonprod' }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Test'
        run: |
          echo "This is: ${{ vars.SERVICE_ACCOUNT }}"

